### ISSUE TITLE
Example of Inheritance

### ISSUE THREAD

**Issue by haifenghuang** [curif/oop4c#1]
Dear sir, I've found your oop4c very good, and the example also very clear. But in the `ooSimple.h` header file, 
I've found `ooClassH`, `ooMethodInitOverride`, `ooMethodOverride`, `ooThisDeclare`, `ooBase`, `ooBaseDeclare`, `ooCall`, `ooCallSuper`  macros, I think it is for class inheritance, but i don't know how to use them, could you please kindly give me some examples, I'll be very much appreciated!  

By the way, I think below macro:  

``` c
#define ooCallSuperS(_obj, _name, _params...) (_obj)->base._name((_obj), ##params)
```

should be

``` c
#define ooCallSuperS(_obj, _name, _params...) (_obj).base._name((_obj), ##params)
```

Am i right?

**Comment by curif** [comment]
Dear friend, sorry for my late response, I was on my holidays. 

For class inheritance you need to declare the class using the H suffix (remember the D suffix is for __ooClass declaration).

Suppose you have a class named myBaseClass you need to inherit.

Example.h

``` c
//derived class declaration.
#undef _ooClass
#define _ooClass myDerivedClass
ooClassDH(myBaseClass)
   int ooMethodDeclareD(myNewMethod, int aParameter); //a new method in myDerivedClass
ooClassEndD

ooCtorD();
ooDtorD();

```

Example.c

``` c

//derived method.
void ooMethodOverrideD(myBaseClass, aBaseMethod) {
  ooThisDeclareD();
  // you can use this-> and ooBase()-> here.
  return;
}

//new method declaration
void ooMethodD(myNewMethod, int aParameter) {
 ooThisDeclareD();
 return;
}

//constructor
ooCtorD() {
  ooInit(myBaseClass, ooBase());
  ooMethodInitOverrideD(aBaseMethod); //to  override a myBaseClass class method.
  ooMethodInitD(myNewMethod); //to init a myDerivedClass class method
  return;
}

```

I hope this help.

**Comment by haifenghuang** [comment]
Thanks very much for the explanation!
